<?php

namespace SLMP\lib\fields;

class acf_fields {

	public function __construct() {
		$this->slmp_acf_widget_fields();
        $this->slmp_acf_gallery_fields();
	}

	public function slmp_acf_widget_fields() {
		if( function_exists('acf_add_local_field_group') ):

		acf_add_local_field_group(array(
			'key' => 'slmp_widget',
			'title' => 'repeater',
			'fields' => array(
				array(
					'key' 		=> 'slmp_widget_gallery_id',
					'label' 	=> 'Select SMLP Gallery',
					'name' 		=> 'widget_gallery_id',
					'type' 		=> 'post_object',
				    'instructions' 			=> '',
				    'required' 				=> 0,
				    'conditional_logic' 	=> 0,
				    'post_type' => array(
						'post_type'			=> 'slmp_gallery_post'
					),
				    'allow_null' 		=> 1,
				    'multiple' 			=> 0,
				    'return_format' 	=> 'id',
				),
				array(
					'key' 		=> 'slmp_widget_gallery_button',
					'label' 	=> 'Gallery Button Label',
					'name' 		=> 'widget_gallery_button',
					'type' 		=> 'text',
					'instructions' 		=> '',
					'required' 			=> 0,
					'conditional_logic' => 0,
					'placeholder' 		=> '',
				),
				array(
					'key' 		=> 'slmp_widget_gallery_page',
					'label' 	=> 'SLMP Button Page Destination',
					'name' 		=> 'widget_gallery_page',
					'type' 		=> 'page_link',
				    'instructions' 			=> '',
				    'required' 				=> 0,
				    'conditional_logic' 	=> 0,
				    'post_type' => array(
						'post_type'			=> 'page'
					),
				    'allow_null' 		=> 1,
				    'allow_archives' 	=> 0,
				    'multiple' 			=> 0,
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'widget',
						'operator' => '==',
						'value' => 'slmp_widget_gallery',
					),
				),
			),
			'menu_order' 			=> 0,
			'position' 				=> 'normal',
			'style' 				=> 'default',
			'label_placement' 		=> 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' 		=> '',
			'active' 				=> true,
			'description' 			=> '',
		));

		endif;
	}

	public function slmp_acf_gallery_fields() {

		if( function_exists('acf_add_local_field_group') ):

			acf_add_local_field_group(array(
				'key' 		=> 'slmp_gallery',
				'title' 	=> '<span class="dashicons dashicons-format-gallery"></span> SLMP Gallery Generator',
				'fields' 	=> array(
					array(
						'key' 		=> 'slmp_gallery_tab1',
						'label' 	=> 'SLMP Gallery Details',
						'name' 		=> 'gallery_tab1',
						'type' 		=> 'tab',
						'placement' => 'left',
						'endpoint' 	> 0,
					),
					array(
						'key' 		=> 'slmp_select_gallery',
						'label' 	=> 'Select Type Of Gallery',
						'name' 		=> 'gallery_type',
						'type' 		=> 'radio',
						'instructions' 		=> '',
						'required' 			=> 0,
						'conditional_logic' => 0,
						'choices' 			=> array(
							'grid'					=> 'Grid Gallery',
							'category'				=> 'Category Gallery',
							'slide'					=> 'Slide Gallery',
							'navigation'			=> 'Navigation Gallery',
							'before_after'			=> 'Before & After Gallery',
							'before_after_slide'	=> 'Before & After Slide Gallery',
							'album'					=> 'Album Gallery',
							'album_slide'			=> 'Album Slide Gallery',
							'album_category'		=> 'Album Category Gallery',
							'masonry'				=> 'Masonry Gallery',
							'video_grid'			=> 'Video Grid Gallery',
							'video_slide'			=> 'Video Slider Gallery',
						),
						'wrapper' 	=> [
					        'class' 	=> 'slmp-gallery-select',
					    ],
						'allow_null' 	=> 1,
						'layout' 		=> 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' 		=> 'slmp_gallery_details',
						'label' 	=> 'Gallery Details',
						'name' 		=> 'gallery_details',
						'type' 		=> 'group',
						'conditional_logic' => array (
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '!=',
								'value' 		=> '',
								),
							),
						),
						'sub_fields' 		=> array(
							array(
								'key' 		=> 'slmp_gallery_title',
								'label' 	=> 'Gallery Title',
								'name' 		=> 'gallery_title',
								'type' 		=> 'text',
								'instructions' 		=> '',
								'required' 			=> 0,
								'conditional_logic' => 0,
								'placeholder' 		=> 'Add Gallery Title Here!',
							),
							array(
								'key' 		=> 'slmp_gallery_description',
								'label' 	=> 'Gallery Description',
								'name' 		=> 'gallery_description',
								'type' 		=> 'textarea',
								'instructions' 		=> '',
								'required' 			=> 0,
								'conditional_logic' => 0,
								'rows' 				=> '4',
								'placeholder' 		=> 'Add Gallery Description Here!',
							),
							array(
								'key' 		=> 'grid_slmp_gallery_images',
								'label' 	=> 'Grid Gallery Images',
								'name' 		=> 'grid_gallery_images',
								'type' 		=> 'gallery',
								'instructions' 		=> '',
								'required' 			=> 0,
								'conditional_logic' => array (
									array (
										array (
										'field' 	=> 'slmp_select_gallery',
										'operator' 	=> '==',
										'value' 	=> 'grid',
										),
									),
								),
								'library' => 'all',
							),
							array(
								'key' 		=> 'masonry_slmp_gallery_images',
								'label' 	=> 'masonry Gallery Images',
								'name' 		=> 'masonry_gallery_images',
								'type' 		=> 'gallery',
								'instructions' 		=> '',
								'required' 			=> 0,
								'conditional_logic' => array (
									array (
										array (
										'field' 	=> 'slmp_select_gallery',
										'operator' 	=> '==',
										'value' 	=> 'masonry',
										),
									),
								),
								'library' => 'all',
							),
							array(
								'key' 				=> 'slide_slmp_gallery_images',
								'label' 			=> 'Slide Gallery Images',
								'name' 				=> 'slide_gallery_images',
								'type' 				=> 'gallery',
								'instructions' 		=> '',
								'required' 			=> 0,
								'conditional_logic' => array (
									array (
										array (
										'field' 	=> 'slmp_select_gallery',
										'operator' 	=> '==',
										'value' 	=> 'slide',
										),
									),
								),
								'library' 		=> 'all',
								'preview_size' 	=> 'thumbnail',
							),
							array(
								'key' 		=> 'navigation_slmp_gallery_images',
								'label' 	=> 'Navigation Gallery Images',
								'name' 		=> 'navigation_gallery_images',
								'type' 		=> 'gallery',
								'instructions' 		=> '',
								'required' 			=> 0,
								'conditional_logic' => array (
									array (
										array (
										'field' 	=> 'slmp_select_gallery',
										'operator' 	=> '==',
										'value' 	=> 'navigation',
										),
									),
								),
								'library' 		=> 'all',
								'preview_size' 	=> 'thumbnail',
							),
							array(
								'key' 		=> 'category_slmp_gallery',
								'label' 	=> 'Category Gallery',
								'name' 		=> 'category_gallery',
							    'type' 		=> 'repeater',
							    'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => array (
									array (
										array (
										'field' 	=> 'slmp_select_gallery',
										'operator' 	=> '==',
										'value' 	=> 'category',
										),
									),
								),
							    'layout' 		=> 'block',
							    'button_label' 	=> 'Add Category',
							    'sub_fields' 	=> array(
							    	array(
										'key' 		=> 'slmp_category_accordion',
										'label' 	=> 'Category Details',
										'name' 		=> 'category_accordion',
										'type' 		=> 'accordion',
										'instructions' 		=> '',
									),
							        array(
							            'key'	 		=> 'category_gallery_title',
							            'label' 		=> 'Category Title',
							            'name' 			=> 'category_title',
							            'type' 			=> 'text',
							            'placeholder' 	=> 'Add Category Title Here!',
							        ),
							        array(
										'key' 		=> 'category_slmp_gallery_images',
										'label' 	=> 'Category Gallery Images',
										'name' 		=> 'category_gallery_images',
										'type' 		=> 'gallery',
										'instructions' 		=> '',
										'required' 			=> 0,
										'conditional_logic' => 0,
										'library' 			=> 'all',
										'preview_size' 		=> 'thumbnail',
									),

							    ),
							),
							array(
								'key' 		=> 'bf_slmp_gallery',
								'label' 	=> 'Before & After Gallery',
								'name' 		=> 'bf_gallery',
							    'type' 		=> 'repeater',
							    'instructions' 		=> 'Note: Upload the same image dimension (width/height) for each before and after image to have better image display. ',
							    'required' 			=> 0,
							    'conditional_logic' => array (
									array (
										array (
										'field' 	=> 'slmp_select_gallery',
										'operator' 	=> '==',
										'value' 	=> 'before_after',
										),
									),
								),
							    'layout' 		=> 'table',
							    'button_label' 	=> 'Add Before & After Image',
							    'sub_fields' 	=> array(
							        array(
							            'key'	 			=> 'bf_before_image',
							            'label' 			=> 'Before Image',
							            'name' 				=> 'bf_before',
							            'type' 				=> 'image',
									    'required' 			=> 0,
									    'conditional_logic' => 0,
									    'return_format' 	=> 'array',
									    'preview_size' 		=> 'thumbnail',
									    'library' 			=> 'all',
							        ),
							        array(
										'key'	 			=> 'bf_after_image',
							            'label' 			=> 'After Image',
							            'name' 				=> 'bf_after',
							            'type' 				=> 'image',
									    'required' 			=> 0,
									    'conditional_logic' => 0,
									    'return_format' 	=> 'array',
									    'preview_size' 		=> 'thumbnail',
									    'library' 			=> 'all',
									),

							    ),
							),
							array(
								'key' 		=> 'bf_slide_slmp_gallery',
								'label' 	=> 'Before & After Slide Gallery',
								'name' 		=> 'bf_slide_gallery',
							    'type' 		=> 'repeater',
							    'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => array (
									array (
										array (
										'field' 	=> 'slmp_select_gallery',
										'operator' 	=> '==',
										'value' 	=> 'before_after_slide',
										),
									),
								),
							    'layout' 		=> 'table',
							    'button_label' 	=> 'Add Before & After Image',
							    'sub_fields' 	=> array(
							        array(
							            'key'	 			=> 'bf_slide_before_image',
							            'label' 			=> 'Before Image',
							            'name' 				=> 'bf_slide_before',
							            'type' 				=> 'image',
									    'required' 			=> 0,
									    'conditional_logic' => 0,
									    'return_format' 	=> 'array',
									    'preview_size' 		=> 'thumbnail',
									    'library' 			=> 'all',
							        ),
							        array(
										'key'	 			=> 'bf_slide_after_image',
							            'label' 			=> 'After Image',
							            'name' 				=> 'bf_slide_after',
							            'type' 				=> 'image',
									    'required' 			=> 0,
									    'conditional_logic' => 0,
									    'return_format' 	=> 'array',
									    'preview_size' 		=> 'thumbnail',
									    'library' 			=> 'all',
									),

							    ),
							),
							array(
								'key' 		=> 'album_slmp_gallery',
								'label' 	=> 'Album Gallery',
								'name' 		=> 'album_gallery',
							    'type' 		=> 'repeater',
							    'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => array (
									array (
										array (
										'field' 	=> 'slmp_select_gallery',
										'operator' 	=> '==',
										'value' 	=> 'album',
										),
									),
								),
							    'layout' 		=> 'block',
							    'button_label' 	=> 'Add Album',
							    'sub_fields' 	=> array(
							    	array(
										'key' 		=> 'slmp_album_accordion',
										'label' 	=> 'Album Details',
										'name' 		=> 'album_accordion',
										'type' 		=> 'accordion',
										'instructions' 		=> '',
									),
							        array(
							            'key'	 		=> 'album_gallery_title',
							            'label' 		=> 'Album Title',
							            'name' 			=> 'album_title',
							            'type' 			=> 'text',
							            'placeholder' 	=> 'Add Album Title Here!',
							        ),
							        array(
										'key' 		=> 'album_gallery_description',
										'label' 	=> 'Album Description',
										'name' 		=> 'album_description',
										'type' 		=> 'textarea',
										'instructions' 		=> '',
										'required' 			=> 0,
										'conditional_logic' => 0,
										'rows' 				=> '4',
										'placeholder' 		=> 'Add Album Description Here!',
									),
									array(
										'key'	 			=> 'album_featured_image',
							            'label' 			=> 'Album Featured Image',
							            'name' 				=> 'album_featured',
							            'type' 				=> 'image',
									    'required' 			=> 0,
									    'conditional_logic' => 0,
									    'return_format' 	=> 'array',
									    'preview_size' 		=> 'thumbnail',
									    'library' 			=> 'all',
									),
							        array(
										'key' 		=> 'album_slmp_gallery_images',
										'label' 	=> 'Album Gallery Images',
										'name' 		=> 'album_gallery_images',
										'type' 		=> 'gallery',
										'instructions' 		=> '',
										'required' 			=> 0,
										'conditional_logic' => 0,
										'library' 			=> 'all',
										'preview_size' 		=> 'thumbnail',
									),

							    ),
							),
							array(
								'key' 		=> 'album_slide_slmp_gallery',
								'label' 	=> 'Album Slide Gallery',
								'name' 		=> 'album_slide_gallery',
							    'type' 		=> 'repeater',
							    'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => array (
									array (
										array (
										'field' 	=> 'slmp_select_gallery',
										'operator' 	=> '==',
										'value' 	=> 'album_slide',
										),
									),
								),
							    'layout' 		=> 'block',
							    'button_label' 	=> 'Add Album',
							    'sub_fields' 	=> array(
							    	array(
										'key' 		=> 'slmp_slide_album_accordion',
										'label' 	=> 'Album Details',
										'name' 		=> 'slide_album_accordion',
										'type' 		=> 'accordion',
										'instructions' 		=> '',
									),
							        array(
							            'key'	 		=> 'album_slide_gallery_title',
							            'label' 		=> 'Album Title',
							            'name' 			=> 'album_slide_title',
							            'type' 			=> 'text',
							            'placeholder' 	=> 'Add Album Title Here!',
							        ),
							        array(
										'key' 		=> 'album_slide_gallery_description',
										'label' 	=> 'Album Description',
										'name' 		=> 'album_slide_description',
										'type' 		=> 'textarea',
										'instructions' 		=> '',
										'required' 			=> 0,
										'conditional_logic' => 0,
										'rows' 				=> '4',
										'placeholder' 		=> 'Add Album Description Here!',
									),
									array(
										'key'	 			=> 'album_slide_featured_image',
							            'label' 			=> 'Album Featured Image',
							            'name' 				=> 'album_slide_featured',
							            'type' 				=> 'image',
									    'required' 			=> 0,
									    'conditional_logic' => 0,
									    'return_format' 	=> 'array',
									    'preview_size' 		=> 'thumbnail',
									    'library' 			=> 'all',
									),
							        array(
										'key' 		=> 'album_slide_slmp_gallery_images',
										'label' 	=> 'Album Slide Gallery Images',
										'name' 		=> 'album_slide_gallery_images',
										'type' 		=> 'gallery',
										'instructions' 		=> '',
										'required' 			=> 0,
										'conditional_logic' => 0,
										'library' 			=> 'all',
										'preview_size' 		=> 'thumbnail',
									),

							    ),
							),
							array(
								'key' 		=> 'album_category_slmp_gallery',
								'label' 	=> 'Album Category Gallery',
								'name' 		=> 'album_category_gallery',
							    'type' 		=> 'repeater',
							    'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => array (
									array (
										array (
										'field' 	=> 'slmp_select_gallery',
										'operator' 	=> '==',
										'value' 	=> 'album_category',
										),
									),
								),
							    'layout' 		=> 'block',
							    'button_label' 	=> 'Add Album',
							    'sub_fields' 	=> array(
							    	array(
										'key' 		=> 'slmp_category_album_accordion',
										'label' 	=> 'Album Details',
										'name' 		=> 'category_album_accordion',
										'type' 		=> 'accordion',
										'instructions' 		=> '',
									),
							        array(
							            'key'	 		=> 'album_category_gallery_title',
							            'label' 		=> 'Album Title',
							            'name' 			=> 'album_category_title',
							            'type' 			=> 'text',
							            'placeholder' 	=> 'Add Album Title Here!',
							        ),
							        array(
										'key' 		=> 'album_category_gallery_description',
										'label' 	=> 'Album Description',
										'name' 		=> 'album_category_description',
										'type' 		=> 'textarea',
										'instructions' 		=> '',
										'required' 			=> 0,
										'conditional_logic' => 0,
										'rows' 				=> '4',
										'placeholder' 		=> 'Add Album Description Here!',
									),
									array(
										'key'	 			=> 'album_category_featured_image',
							            'label' 			=> 'Album Featured Image',
							            'name' 				=> 'album_category_featured',
							            'type' 				=> 'image',
									    'required' 			=> 0,
									    'conditional_logic' => 0,
									    'return_format' 	=> 'array',
									    'preview_size' 		=> 'thumbnail',
									    'library' 			=> 'all',
									),
									array(
										'key'	 			=> 'album_category_list_items',
							            'label' 			=> 'Album Category',
							            'name' 				=> 'album_category_item',
							            'type' 				=> 'checkbox',
									    'instructions' 		=> 'Note: Add Categories Here!',
									    'required' 			=> 0,
									    'conditional_logic' => 0,
									    'choices' 			=> [
									    ],
									    'allow_custom' 		=> 1,
									    'save_custom' 		=> 0,
									    'layout' 			=> 'vertical',
									    'toggle' 			=> 1,
									    'return_format' 	=> 'value',
									),
							        array(
										'key' 		=> 'album_category_slmp_gallery_images',
										'label' 	=> 'Album Category Gallery Images',
										'name' 		=> 'album_category_gallery_images',
										'type' 		=> 'gallery',
										'instructions' 		=> '',
										'required' 			=> 0,
										'conditional_logic' => 0,
										'library' 			=> 'all',
										'preview_size' 		=> 'thumbnail',
									),

							    ),
							),
							array(
								'key' 		=> 'video_slide_slmp_gallery',
								'label' 	=> 'Video Slide Gallery',
								'name' 		=> 'video_slide_gallery',
							    'type' 		=> 'repeater',
							    'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => array (
									array (
										array (
										'field' 	=> 'slmp_select_gallery',
										'operator' 	=> '==',
										'value' 	=> 'video_slide',
										),
									),
								),
							    'layout' 		=> 'block',
							    'button_label' 	=> 'Add Video',
							    'sub_fields' 	=> array(
							    	array(
										'key' 		=> 'slmp_video_slide_accordion',
										'label' 	=> 'Video Slide Details',
										'name' 		=> 'video_slide_accordion',
										'type' 		=> 'accordion',
										'instructions' 		=> '',
									),
							        array(
							            'key'	 			=> 'slmp_video_slide_select',
							            'label' 			=> 'Select Video Type',
							            'name' 				=> 'video_slide_select',
							            'type' 				=> 'select',
									    'required' 			=> 0,
									    'conditional_logic' => 0,
									    'choices' => array(
										    'youtube'   => 'Youtube Video',
										    'local'   	=> 'Local Video'
										),
									    'allow_null' => 1,
									    'ui' => 1,
									    'ajax' => 1,
							        ),
							        array(
							            'key'	 			=> 'slmp_video_slide_thumbnail',
							            'label' 			=> 'Video Thumbnail',
							            'name' 				=> 'video_slide_thumbnail',
							            'type' 				=> 'image',
									    'required' 			=> 0,
									    'conditional_logic' => array (
											array (
												array (
												'field' 	=> 'slmp_video_slide_select',
												'operator' 	=> '!=',
												'value' 	=> '',
												),
											),
										),
									    'preview_size' 		=> 'thumbnail',
									    'return_format' 	=> 'array',
									    'instructions' 		=> 'Note: If youtube video is selected you can use the default youtube video thumbnail by not adding Video thumbnail.',
							        ),
							        array(
							            'key'	 			=> 'slmp_video_slide_url',
							            'label' 			=> 'Video URL',
							            'name' 				=> 'video_slide_url',
							            'type' 				=> 'url',
									    'required' 			=> 0,
									    'conditional_logic' => array (
											array (
												array (
												'field' 	=> 'slmp_video_slide_select',
												'operator' 	=> '!=',
												'value' 	=> '',
												),
											),
										),
									    'instructions' 		=> 'Note: If youtube video is selected add the URL embed URL.',
							        ),
							    ),
							),
							array(
								'key' 		=> 'video_grid_slmp_gallery',
								'label' 	=> 'Video Grid Gallery',
								'name' 		=> 'video_grid_gallery',
							    'type' 		=> 'repeater',
							    'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => array (
									array (
										array (
										'field' 	=> 'slmp_select_gallery',
										'operator' 	=> '==',
										'value' 	=> 'video_grid',
										),
									),
								),
							    'layout' 		=> 'block',
							    'button_label' 	=> 'Add Video',
							    'sub_fields' 	=> array(
							    	array(
										'key' 		=> 'slmp_video_grid_accordion',
										'label' 	=> 'Video Grid Details',
										'name' 		=> 'video_grid_accordion',
										'type' 		=> 'accordion',
										'instructions' 		=> '',
									),
							        array(
							            'key'	 			=> 'slmp_video_grid_select',
							            'label' 			=> 'Select Video Type',
							            'name' 				=> 'video_grid_select',
							            'type' 				=> 'select',
									    'required' 			=> 0,
									    'conditional_logic' => 0,
									    'choices' => array(
										    'youtube'   => 'Youtube Video',
										    'local'   	=> 'Local Video'
										),
									    'allow_null' => 1,
									    'ui' => 1,
									    'ajax' => 1,
							        ),
							        array(
							            'key'	 			=> 'slmp_video_grid_thumbnail',
							            'label' 			=> 'Video Thumbnail',
							            'name' 				=> 'video_grid_thumbnail',
							            'type' 				=> 'image',
									    'required' 			=> 0,
									    'conditional_logic' => array (
											array (
												array (
												'field' 	=> 'slmp_video_grid_select',
												'operator' 	=> '!=',
												'value' 	=> '',
												),
											),
										),
									    'preview_size' 		=> 'thumbnail',
									    'return_format' 	=> 'array',
									    'instructions' 		=> 'Note: If youtube video is selected you can use the default youtube video thumbnail by not adding Video thumbnail.',
							        ),
							        array(
							            'key'	 			=> 'slmp_video_grid_url',
							            'label' 			=> 'Video URL',
							            'name' 				=> 'video_grid_url',
							            'type' 				=> 'url',
									    'required' 			=> 0,
									    'conditional_logic' => array (
											array (
												array (
												'field' 	=> 'slmp_video_grid_select',
												'operator' 	=> '!=',
												'value' 	=> '',
												),
											),
										),
									    'instructions' 		=> 'Note: If youtube video is selected add the URL embed URL.',
							        ),
							    ),
							),
						),
					),
					array(
						'key' 		=> 'slmp_gallery_tab2',
						'label' 	=> 'SLMP Gallery Display Setting',
						'name' 		=> 'gallery_tab2',
						'type' 		=> 'tab',
						'placement' => 'left',
						'conditional_logic' => array (
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '!=',
								'value' 		=> '',
								),
							),
						),
						'endpoint' 	> 0,
					),
					array(
						'key' 		=> 'slmp_category_nav_style',
						'label' 	=> 'Select Category Navigation Style',
						'name' 		=> 'category_nav_style',
						'type' 		=> 'select',
						'instructions' 		=> 'Note: Default value is "List Navigation Style".',
						'required' 			=> 0,
						'conditional_logic' => array (
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'category',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'album_category',
								),
							),
						),
						'choices' 			=> array(
							'list'			=> 'List Navigation Style',
							'dropdown'		=> 'Dropdown Navigation Style',
						),
						'allow_null' 	=> 1,
					    'ui' 			=> 1,
					    'ajax' 			=> 1,
					    'return_format' => 'value',
					    'placeholder' 	=> 'Select Category Navigation Style',
					),
					array(
						'key' 		=> 'slmp_image_column',
						'label' 	=> 'Select Number of Column',
						'name' 		=> 'image_column',
						'type' 		=> 'select',
						'instructions' 		=> 'Note: Default Column number is "3".',
						'required' 			=> 0,
						'conditional_logic' => array (
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'grid',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'masonry',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'category',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'album',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'album_category',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'video_grid',
								),
							),
						),
						'choices' 			=> array(
							'4'				=> '4 Column',
							'3'				=> '3 Column',
							'2'				=> '2 Column',
							'1'				=> '1 Column',
						),
						'allow_null' 	=> 1,
					    'ui' 			=> 1,
					    'ajax' 			=> 1,
					    'return_format' => 'value',
					    'placeholder' 	=> 'Select Number of image column!',
					),
					array(
						'key' 		=> 'slmp_image_thumbnail',
						'label' 	=> 'Select Image Thumbnail Size',
						'name' 		=> 'image_thumbnail',
						'type' 		=> 'select',
						'instructions' 		=> 'Note: Default thumbnail is "SLMP Thumbnail".',
						'required' 			=> 0,
						'conditional_logic' => 0,
						'choices' 			=> array(
							'full'				=> 'Full Image',
							'slmp_thumbnail'	=> 'SLMP Thumbnail',
							'thumbnail'			=> 'Thumbnail',
						),
						'allow_null' 	=> 1,
					    'ui' 			=> 1,
					    'ajax' 			=> 1,
					    'return_format' => 'value',
					    'placeholder' 	=> 'Select Image Thumbnail Size!',
					),
					array(
						'key' 		=> 'slmp_image_display_title',
						'label' 	=> 'Display Image Title',
						'name' 		=> 'display_title',
						'type' 		=> 'true_false',
						'instructions' 		=> 'Note: Enable this to diplay "Image Title" of the image.',
					    'required' 			=> 0,
					    'conditional_logic' => array (
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'grid',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'masonry',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'category',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'slide',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'navigation',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'album',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'album_slide',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'album_category',
								),
							),
						),
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_image_zoom',
						'label' 	=> 'Display Zoom Icon When Hover',
						'name' 		=> 'image_zoom',
						'type' 		=> 'true_false',
						'instructions' 		=> 'Note: Enable this to diplay "Zoom Icon" when image is hover.',
					    'required' 			=> 0,
					    'conditional_logic' => array (
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'grid',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'masonry',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'category',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'slide',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'navigation',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'album',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'album_slide',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'album_category',
								),
							),
						),
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_load_more_image',
						'label' 	=> 'Display Load More Button',
						'name' 		=> 'load_more_image',
						'type' 		=> 'true_false',
						'instructions' 		=> 'Note: Enable this to diplay "Load More" button.',
					    'required' 			=> 0,
					    'conditional_logic' => array (
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'grid',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'category',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'album',
								),
							),
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '==',
								'value' 		=> 'album_category',
								),
							),
						),
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_load_more_display',
						'label' 	=> 'Display Images First Load',
						'name' 		=> 'load_more_display',
						'type' 		=> 'number',
						'instructions' 		=> 'Note: Default value is "9"',
					    'required' 			=> 0,
					    'conditional_logic' => array (
							array (
								array (
								'field' 	=> 'slmp_load_more_image',
								'operator' 	=> '==',
								'value' 	=> 1,
								),
							),
						),
						'default_value'		=> '9',
					    'placeholder' 		=> 'Default Number 9',
					),
					array(
						'key' 		=> 'slmp_load_more_loaded',
						'label' 	=> 'Display Images To be Loaded',
						'name' 		=> 'load_more_loaded',
						'type' 		=> 'number',
						'instructions' 		=> 'Note: Default value is "6"',
					    'required' 			=> 0,
					    'conditional_logic' => array (
							array (
								array (
								'field' 	=> 'slmp_load_more_image',
								'operator' 	=> '==',
								'value' 	=> 1,
								),
							),
						),
						'default_value'		=> '6',
					    'placeholder' 		=> 'Default Number 6',
					),
					array(
						'key' 		=> 'slmp_load_more_label',
						'label' 	=> 'SLMP Load More Label',
						'name' 		=> 'load_more_label',
						'type' 		=> 'text',
						'instructions' 		=> '',
						'required' 			=> 0,
						'conditional_logic' => array (
							array (
								array (
								'field' 	=> 'slmp_load_more_image',
								'operator' 	=> '==',
								'value' 	=> 1,
								),
							),
						),
						'placeholder' 		=> 'Add Load More Label Here!',
					),
					array(
						'key' 		=> 'slmp_gallery_tab3',
						'label' 	=> 'SLMP Gallery Slide Setting',
						'name' 		=> 'gallery_tab3',
						'type' 		=> 'tab',
						'placement' => 'left',
						'conditional_logic' => array (
							array (
								array (
									'field' 	=> 'slmp_select_gallery',
									'operator' 	=> '==',
									'value' 	=> 'slide',
								)
							),
							array (
								array (
									'field' 	=> 'slmp_select_gallery',
									'operator' 	=> '==',
									'value' 	=> 'album_slide',
								)
							),
							array (
								array (
									'field' 	=> 'slmp_select_gallery',
									'operator' 	=> '==',
									'value' 	=> 'video_slide',
								)
							),
						),
						'endpoint' 	> 0,
					),
					array(
						'key' 		=> 'slmp_slick_message',
						'label' 	=> 'Slick Slider Settings',
						'name' 		=> 'slick_message',
						'type' 		=> 'message',
						'instructions' 		=> '',
						'message' 			=> 'Setup all slick slider setting here!',
					    'new_lines' 		=> 'wpautop',
					    'esc_html' 			=> 0,
					),
					array(
						'key' 		=> 'slmp_slick_dots',
						'label' 	=> 'Enable Slick Dots',
						'name' 		=> 'slick_dots',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_infinite',
						'label' 	=> 'Enable Slick Infinite Scroll',
						'name' 		=> 'slick_infinite',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_fade',
						'label' 	=> 'Enable Slick Fade',
						'name' 		=> 'slick_fade',
						'type' 		=> 'true_false',
						'instructions' 		=> 'Note: Fade effect will not work if "slidesToShow" in setting is more than "1" you should disable it.',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_pauseOnHover',
						'label' 	=> 'Enable Slick Pause On Hover',
						'name' 		=> 'slick_pauseOnHover',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_autoplay',
						'label' 	=> 'Enable Slick Autoplay',
						'name' 		=> 'slick_autoplay',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_adaptiveHeight',
						'label' 	=> 'Enable Slick Adaptive Height',
						'name' 		=> 'slick_adaptiveHeight',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_centerMode',
						'label' 	=> 'Enable Slick Center Mode',
						'name' 		=> 'slick_centerMode',
						'type' 		=> 'true_false',
						'instructions' 		=> 'Note: When Center Mode is active "slidesToScroll" is always "1" even though you set a number for it.',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_slidesToShow',
						'label' 	=> 'Slick Slides To Show',
						'name' 		=> 'slick_slidesToShow',
						'type' 		=> 'number',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
						'default_value'		=> '1',
					    'placeholder' 		=> 'Default Number 1',
					),
					array(
						'key' 		=> 'slmp_slick_slidesToScroll',
						'label' 	=> 'Slick Slides To Scroll',
						'name' 		=> 'slick_slidesToScroll',
						'type' 		=> 'number',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
						'default_value'		=> '1',
					    'placeholder' 		=> 'Default Number 1',
					),
					array(
						'key' 		=> 'slmp_slick_speed',
						'label' 	=> 'Slick Slides speed',
						'name' 		=> 'slick_speed',
						'type' 		=> 'number',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
						'default_value'		=> '500',
					    'placeholder' 		=> 'Default Number 500',
					),
					array(
						'key' 		=> 'slmp_slick_autoplaySpeed',
						'label' 	=> 'Slick Slides Autoplay Speed',
						'name' 		=> 'slick_autoplaySpeed',
						'type' 		=> 'number',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
						'default_value'		=> '5000',
					    'placeholder' 		=> 'Default Number 5000',
					),
					array(
						'key' 		=> 'slmp_slick_first_responsive',
						'label' 	=> 'Slick Slides Responsive First Breakpoint',
						'name' 		=> 'slick_first_responsive',
						'type' 		=> 'group',
						'layout' 	=> 'table',
						'conditional_logic' => 0,
						'sub_fields' 		=> array(
							array(
								'key' 		=> 'slmp_slick_first_breakpoint',
								'label' 	=> 'Slick Slides Breakpoint',
								'name' 		=> 'slick_first_breakpoint',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1024',
							    'placeholder' 		=> 'Default Number 1024',
							),
							array(
								'key' 		=> 'slmp_slick_first_slidesToShow',
								'label' 	=> 'Slick Slides Slides To Show',
								'name' 		=> 'slick_first_slidesToShow',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1',
							    'placeholder' 		=> 'Default Number 1',
							),
							array(
								'key' 		=> 'slmp_slick_first_slidesToScroll',
								'label' 	=> 'Slick Slides Slides To Scroll',
								'name' 		=> 'slick_first_slidesToScroll',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1',
							    'placeholder' 		=> 'Default Number 1',
							),
						),
					),
					array(
						'key' 		=> 'slmp_slick_second_responsive',
						'label' 	=> 'Slick Slides Responsive Second Breakpoint',
						'name' 		=> 'slick_second_responsive',
						'type' 		=> 'group',
						'layout' 	=> 'table',
						'conditional_logic' => 0,
						'sub_fields' 		=> array(
							array(
								'key' 		=> 'slmp_slick_second_breakpoint',
								'label' 	=> 'Slick Slides Breakpoint',
								'name' 		=> 'slick_second_breakpoint',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '768',
							    'placeholder' 		=> 'Default Number 768',
							),
							array(
								'key' 		=> 'slmp_slick_second_slidesToShow',
								'label' 	=> 'Slick Slides Slides To Show',
								'name' 		=> 'slick_second_slidesToShow',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1',
							    'placeholder' 		=> 'Default Number 1',
							),
							array(
								'key' 		=> 'slmp_slick_second_slidesToScroll',
								'label' 	=> 'Slick Slides Slides To Scroll',
								'name' 		=> 'slick_second_slidesToScroll',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1',
							    'placeholder' 		=> 'Default Number 1',
							),
						),
					),
					array(
						'key' 		=> 'slmp_slick_third_responsive',
						'label' 	=> 'Slick Slides Responsive Third Breakpoint',
						'name' 		=> 'slick_third_responsive',
						'type' 		=> 'group',
						'layout' 	=> 'table',
						'conditional_logic' => 0,
						'sub_fields' 		=> array(
							array(
								'key' 		=> 'slmp_slick_third_breakpoint',
								'label' 	=> 'Slick Slides Breakpoint',
								'name' 		=> 'slick_third_breakpoint',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '480',
							    'placeholder' 		=> 'Default Number 480',
							),
							array(
								'key' 		=> 'slmp_slick_third_slidesToShow',
								'label' 	=> 'Slick Slides Slides To Show',
								'name' 		=> 'slick_third_slidesToShow',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1',
							    'placeholder' 		=> 'Default Number 1',
							),
							array(
								'key' 		=> 'slmp_slick_third_slidesToScroll',
								'label' 	=> 'Slick Slides Slides To Scroll',
								'name' 		=> 'slick_third_slidesToScroll',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1',
							    'placeholder' 		=> 'Default Number 1',
							),
						),
					),
					array(
						'key' 		=> 'slmp_gallery_tab4',
						'label' 	=> 'SLMP Gallery Navigation Setting',
						'name' 		=> 'gallery_tab4',
						'type' 		=> 'tab',
						'placement' => 'left',
						'conditional_logic' => array (
							array (
								array (
									'field' 	=> 'slmp_select_gallery',
									'operator' 	=> '==',
									'value' 	=> 'navigation',
								)
							),
						),
						'endpoint' 	> 0,
					),
					array(
						'key' 		=> 'slmp_slick_nav_message',
						'label' 	=> 'Slick Slider Navigation Settings',
						'name' 		=> 'slick_nav_message',
						'type' 		=> 'message',
						'instructions' 		=> '',
						'message' 			=> 'Setup all slick slider navigation setting here!',
					    'new_lines' 		=> 'wpautop',
					    'esc_html' 			=> 0,
					),
					array(
						'key' 		=> 'slmp_slick_nav_dots',
						'label' 	=> 'Enable Slick Dots',
						'name' 		=> 'slick_nav_dots',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_nav_infinite',
						'label' 	=> 'Enable Slick Infinite Scroll',
						'name' 		=> 'slick_nav_infinite',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_nav_fade',
						'label' 	=> 'Enable Slick Fade',
						'name' 		=> 'slick_nav_fade',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_nav_focusOnSelect',
						'label' 	=> 'Enable Slick Focus On Select',
						'name' 		=> 'slick_nav_focusOnSelect',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_nav_pauseOnHover',
						'label' 	=> 'Enable Slick Pause On Hover',
						'name' 		=> 'slick_nav_pauseOnHover',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_nav_autoplay',
						'label' 	=> 'Enable Slick Autoplay',
						'name' 		=> 'slick_nav_autoplay',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_nav_adaptiveHeight',
						'label' 	=> 'Enable Slick Adaptive Height',
						'name' 		=> 'slick_nav_adaptiveHeight',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_nav_centerMode',
						'label' 	=> 'Enable Slick Center Mode',
						'name' 		=> 'slick_nav_centerMode',
						'type' 		=> 'true_false',
						'instructions' 		=> 'Note: When Center Mode is active "slidesToScroll" is always "1" even though you set a number for it.',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_nav_slidesToShow',
						'label' 	=> 'Slick Slides To Show',
						'name' 		=> 'slick_nav_slidesToShow',
						'type' 		=> 'number',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
						'default_value'		=> '1',
					    'placeholder' 		=> 'Default Number 1',
					),
					array(
						'key' 		=> 'slmp_slick_nav_slidesToScroll',
						'label' 	=> 'Slick Slides To Scroll',
						'name' 		=> 'slick_nav_slidesToScroll',
						'type' 		=> 'number',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
						'default_value'		=> '1',
					    'placeholder' 		=> 'Default Number 1',
					),
					array(
						'key' 		=> 'slmp_slick_nav_speed',
						'label' 	=> 'Slick Slides speed',
						'name' 		=> 'slick_nav_speed',
						'type' 		=> 'number',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
						'default_value'		=> '500',
					    'placeholder' 		=> 'Default Number 500',
					),
					array(
						'key' 		=> 'slmp_slick_nav_autoplaySpeed',
						'label' 	=> 'Slick Slides Autoplay Speed',
						'name' 		=> 'slick_nav_autoplaySpeed',
						'type' 		=> 'number',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
						'default_value'		=> '5000',
					    'placeholder' 		=> 'Default Number 5000',
					),
					array(
						'key' 		=> 'slmp_slick_nav_first_responsive',
						'label' 	=> 'Slick Slides Responsive First Breakpoint',
						'name' 		=> 'slick_nav_first_responsive',
						'type' 		=> 'group',
						'layout' 	=> 'table',
						'conditional_logic' => 0,
						'sub_fields' 		=> array(
							array(
								'key' 		=> 'slmp_slick_nav_first_breakpoint',
								'label' 	=> 'Slick Slides Breakpoint',
								'name' 		=> 'slick_nav_first_breakpoint',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1024',
							    'placeholder' 		=> 'Default Number 1024',
							),
							array(
								'key' 		=> 'slmp_slick_nav_first_slidesToShow',
								'label' 	=> 'Slick Slides Slides To Show',
								'name' 		=> 'slick_nav_first_slidesToShow',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1',
							    'placeholder' 		=> 'Default Number 1',
							),
							array(
								'key' 		=> 'slmp_slick_nav_first_slidesToScroll',
								'label' 	=> 'Slick Slides Slides To Scroll',
								'name' 		=> 'slick_nav_first_slidesToScroll',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1',
							    'placeholder' 		=> 'Default Number 1',
							),
						),
					),
					array(
						'key' 		=> 'slmp_slick_nav_second_responsive',
						'label' 	=> 'Slick Slides Responsive Second Breakpoint',
						'name' 		=> 'slick_nav_second_responsive',
						'type' 		=> 'group',
						'layout' 	=> 'table',
						'conditional_logic' => 0,
						'sub_fields' 		=> array(
							array(
								'key' 		=> 'slmp_slick_nav_second_breakpoint',
								'label' 	=> 'Slick Slides Breakpoint',
								'name' 		=> 'slick_nav_second_breakpoint',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '768',
							    'placeholder' 		=> 'Default Number 768',
							),
							array(
								'key' 		=> 'slmp_slick_nav_second_slidesToShow',
								'label' 	=> 'Slick Slides Slides To Show',
								'name' 		=> 'slick_nav_second_slidesToShow',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1',
							    'placeholder' 		=> 'Default Number 1',
							),
							array(
								'key' 		=> 'slmp_slick_nav_second_slidesToScroll',
								'label' 	=> 'Slick Slides Slides To Scroll',
								'name' 		=> 'slick_nav_second_slidesToScroll',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1',
							    'placeholder' 		=> 'Default Number 1',
							),
						),
					),
					array(
						'key' 		=> 'slmp_slick_nav_third_responsive',
						'label' 	=> 'Slick Slides Responsive Third Breakpoint',
						'name' 		=> 'slick_nav_third_responsive',
						'type' 		=> 'group',
						'layout' 	=> 'table',
						'conditional_logic' => 0,
						'sub_fields' 		=> array(
							array(
								'key' 		=> 'slmp_slick_nav_third_breakpoint',
								'label' 	=> 'Slick Slides Breakpoint',
								'name' 		=> 'slick_nav_third_breakpoint',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '480',
							    'placeholder' 		=> 'Default Number 480',
							),
							array(
								'key' 		=> 'slmp_slick_nav_third_slidesToShow',
								'label' 	=> 'Slick Slides Slides To Show',
								'name' 		=> 'slick_nav_third_slidesToShow',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1',
							    'placeholder' 		=> 'Default Number 1',
							),
							array(
								'key' 		=> 'slmp_slick_nav_third_slidesToScroll',
								'label' 	=> 'Slick Slides Slides To Scroll',
								'name' 		=> 'slick_nav_third_slidesToScroll',
								'type' 		=> 'number',
								'instructions' 		=> '',
							    'required' 			=> 0,
							    'conditional_logic' => 0,
								'default_value'		=> '1',
							    'placeholder' 		=> 'Default Number 1',
							),
						),
					),
					array(
						'key' 		=> 'slmp_gallery_tab5',
						'label' 	=> 'SLMP Gallery Before & After Slide Setting',
						'name' 		=> 'gallery_tab5',
						'type' 		=> 'tab',
						'placement' => 'left',
						'conditional_logic' => array (
							array (
								array (
									'field' 	=> 'slmp_select_gallery',
									'operator' 	=> '==',
									'value' 	=> 'before_after_slide',
								)
							),
						),
						'endpoint' 	> 0,
					),
					array(
						'key' 		=> 'slmp_slick_bf_message',
						'label' 	=> 'Slick Slider Navigation Settings',
						'name' 		=> 'slick_bf_message',
						'type' 		=> 'message',
						'instructions' 		=> '',
						'message' 			=> 'Setup all slick slider before & after slide setting here!',
					    'new_lines' 		=> 'wpautop',
					    'esc_html' 			=> 0,
					),
					array(
						'key' 		=> 'slmp_slick_bf_dots',
						'label' 	=> 'Enable Slick Dots',
						'name' 		=> 'slick_bf_dots',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_bf_infinite',
						'label' 	=> 'Enable Slick Infinite Scroll',
						'name' 		=> 'slick_bf_infinite',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_bf_fade',
						'label' 	=> 'Enable Slick Fade',
						'name' 		=> 'slick_bf_fade',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_bf_pauseOnHover',
						'label' 	=> 'Enable Slick Pause On Hover',
						'name' 		=> 'slick_bf_pauseOnHover',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_bf_autoplay',
						'label' 	=> 'Enable Slick Autoplay',
						'name' 		=> 'slick_bf_autoplay',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_bf_adaptiveHeight',
						'label' 	=> 'Enable Slick Adaptive Height',
						'name' 		=> 'slick_bf_adaptiveHeight',
						'type' 		=> 'true_false',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
					    'message' 			=> '',
					    'default_value' 	=> 0,
					    'ui' 				=> 1,
					    'ui_on_text' 		=> 'Yes',
					    'ui_off_text' 		=> 'No',
					),
					array(
						'key' 		=> 'slmp_slick_bf_speed',
						'label' 	=> 'Slick Slides speed',
						'name' 		=> 'slick_bf_speed',
						'type' 		=> 'number',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
						'default_value'		=> '500',
					    'placeholder' 		=> 'Default Number 500',
					),
					array(
						'key' 		=> 'slmp_slick_bf_autoplaySpeed',
						'label' 	=> 'Slick Slides Autoplay Speed',
						'name' 		=> 'slick_bf_autoplaySpeed',
						'type' 		=> 'number',
						'instructions' 		=> '',
					    'required' 			=> 0,
					    'conditional_logic' => 0,
						'default_value'		=> '5000',
					    'placeholder' 		=> 'Default Number 5000',
					),
					array(
						'key' 		=> 'slmp_gallery_tab6',
						'label' 	=> 'SLMP Gallery Shortcode',
						'name' 		=> 'gallery_tab6',
						'type' 		=> 'tab',
						'placement' => 'left',
						'conditional_logic' => array (
							array (
								array (
								'field' 		=> 'slmp_select_gallery',
								'operator' 		=> '!=',
								'value' 		=> '',
								),
							),
						),
						'endpoint' 	> 0,
					),
					array(
						'key' 		=> 'slmp_gallery_shortcode',
						'label' 	=> 'Gallery Shortcode',
						'name' 		=> 'gallery_shortcode',
						'type' 		=> 'text',
						'instructions' 		=> 'Note: Shortcode will generate after you save the gallery.',
						'required' 			=> 0,
						'conditional_logic' => 0,
						'placeholder' 		=> '',
						'readonly' 			=> 1,
					),
				),
				'location' => array (
					array (
						array (
							'param' 		=> 'post_type',
							'operator' 		=> '==',
							'value' 		=> 'slmp_gallery_post',
						),
					),
				),
				'menu_order' 			=> 0,
				'position' 				=> 'normal',
				'style' 				=> 'default',
				'label_placement' 		=> 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' 		=> '',
				'active' 				=> true,
				'description' 			=> '',
			));

		endif;

	}

}